# Generated by Django 5.0.2 on 2024-05-05 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_alter_studentprofile_options_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="studentprofile",
            table="student_profiles",
        ),
        migrations.AlterModelTable(
            name="teacherprofile",
            table="teacher_profiles",
        ),
    ]
