# Generated by Django 5.0.2 on 2024-05-09 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0004_alter_studentprofile_user_alter_teacherprofile_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentprofile",
            name="avatar",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="student-avatars/",
                verbose_name="фото профиля",
            ),
        ),
        migrations.AlterField(
            model_name="studentprofile",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="дата создания"),
        ),
        migrations.AlterField(
            model_name="studentprofile",
            name="faculty",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="факультет"
            ),
        ),
        migrations.AlterField(
            model_name="studentprofile",
            name="father_name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="отчество"
            ),
        ),
        migrations.AlterField(
            model_name="studentprofile",
            name="group",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="группа"
            ),
        ),
        migrations.AlterField(
            model_name="studentprofile",
            name="name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="имя"
            ),
        ),
        migrations.AlterField(
            model_name="studentprofile",
            name="surname",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="фамилия"
            ),
        ),
        migrations.AlterField(
            model_name="teacherprofile",
            name="avatar",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="teacher-avatars/",
                verbose_name="фото профиля",
            ),
        ),
        migrations.AlterField(
            model_name="teacherprofile",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="дата создания"),
        ),
        migrations.AlterField(
            model_name="teacherprofile",
            name="faculty",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="факультет"
            ),
        ),
        migrations.AlterField(
            model_name="teacherprofile",
            name="father_name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="отчество"
            ),
        ),
        migrations.AlterField(
            model_name="teacherprofile",
            name="name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="имя"
            ),
        ),
        migrations.AlterField(
            model_name="teacherprofile",
            name="surname",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="фамилия"
            ),
        ),
    ]
