# Generated by Django 5.0.2 on 2024-05-03 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="answer",
            options={"verbose_name": "ответ", "verbose_name_plural": "ответы"},
        ),
        migrations.AlterModelOptions(
            name="answerfile",
            options={
                "verbose_name": "файл ответа",
                "verbose_name_plural": "файлы ответов",
            },
        ),
        migrations.AlterModelOptions(
            name="question",
            options={"verbose_name": "вопрос", "verbose_name_plural": "вопросы"},
        ),
        migrations.AlterModelOptions(
            name="questionfile",
            options={
                "verbose_name": "файл вопроса",
                "verbose_name_plural": "файлы вопросов",
            },
        ),
    ]
