# Generated by Django 5.0.6 on 2024-05-23 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0004_alter_answer_answer_text_alter_answer_is_correct_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="questionfile",
            old_name="question_file",
            new_name="file",
        ),
    ]
