# Generated by Django 5.0.6 on 2024-05-23 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0005_rename_question_file_questionfile_file"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="answer",
            table="answersq",
        ),
    ]
