# Generated by Django 5.0.6 on 2024-05-23 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0006_alter_answer_table"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="answer",
            table="answers",
        ),
    ]
