repos:
  - repo: "https://github.com/pre-commit/pre-commit-hooks"
    rev: "v4.5.0"
    hooks: []

  - repo: "https://github.com/psf/black"
    rev: "stable"
    hooks:
      - id: black

  - repo: "https://github.com/pre-commit/mirrors-autopep8"
    rev: "v2.0.4"
    hooks:
      - id: autopep8

  - repo: "https://github.com/PyCQA/autoflake"
    rev: "v2.2.1"
    hooks:
      - id: autoflake
        args: ["--remove-all-unused-imports"]

  - repo: "https://github.com/PyCQA/flake8"
    rev: "6.1.0"
    hooks:
      - id: flake8
