repos:
  - repo: "https://github.com/pre-commit/pre-commit-hooks"
    rev: "v4.5.0"
    hooks:
      - id: check-yaml
      - id: trailing-whitespace
      - id: debug-statements
      - id: check-added-large-files

  - repo: "https://github.com/psf/black"
    rev: "stable"
    hooks:
      - id: black

  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: "v2.0.4"
    hooks:
      - id: autopep8

  - repo: https://github.com/PyCQA/autoflake
    rev: v2.2.1
    hooks:
      - id: autoflake
        args: [ "--in-place", "--remove-all-unused-imports", "--remove-unused-variable" ]

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
