repos:
  - repo: "https://github.com/pre-commit/pre-commit-hooks"
    rev: "v4.5.0"
    hooks:
      - id: check-yaml
      - id: trailing-whitespace
      - id: debug-statements
      - id: check-added-large-files

  - repo: "https://github.com/psf/black"
    rev: "stable"
    hooks:
      - id: black

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
