repos:
  - repo: "https://github.com/pre-commit/pre-commit-hooks"
    rev: "v4.5.0"
    hooks:
      - id: check-yaml
      - id: trailing-whitespace
      - id: double-quote-string-fixer
      - id: debug-statements
      - id: check-added-large-files

  - repo: "https://github.com/psf/black"
    rev: "stable"
    hooks:
      - id: black

  - repo: "https://github.com/pre-commit/mirrors-autopep8"
    rev: "v2.0.4"
    hooks:
      - id: autopep8

  - repo: "https://github.com/PyCQA/autoflake"
    rev: "v2.2.1"
    hooks:
      - id: autoflake
        args: [ "--in-place", "--remove-all-unused-imports", "--remove-unused-variable" ]

  - repo: "https://github.com/PyCQA/flake8"
    rev: "6.1.0"
    hooks:
      - id: flake8
        additional_dependencies:
          [
            "flake8-absolute-import",
            "flake8-bugbear",
            "flake8-cognitive-complexity",
            "flake8-django",
            "flake8-eradicate",
            "flake8-fixme",
            "flake8-mock",
            "flake8-multiline-containers",
            "flake8-mutable",
            "flake8-pep3101",
            "flake8-pie",
            "flake8-plugin-utils",
            "flake8-print",
            "flake8-printf-formatting",
            "flake8-pytest-style",
            "flake8-pytest",
            "flake8-simplify",
            "flake8-todo",
            "flake8-use-fstring",
            "flake8-variables-names",
            "flake8-walrus",
          ]
