#services:
#  web-app:
#    build:
#      context: .
#    ports:
#      - "8000:8000"
#    volumes:
#      - ./course-system:/course-system
#
#    command: >
#      sh -c "python manage.py runserver 0.0.0.:8000"