# Generated by Django 5.0.2 on 2024-04-24 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checkpoints", "0003_remove_checkpoint_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passedcheckpoint",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="summary",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
