# Generated by Django 5.0.2 on 2024-05-03 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("checkpoints", "0004_alter_passedcheckpoint_id_alter_summary_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="checkpoint",
            options={
                "verbose_name": "контрольный точка",
                "verbose_name_plural": "контрольные точки",
            },
        ),
        migrations.AlterModelOptions(
            name="passedcheckpoint",
            options={
                "verbose_name": "пройденная контрольная точка",
                "verbose_name_plural": "пройденные контрольные точки",
            },
        ),
        migrations.AlterModelOptions(
            name="summary",
            options={
                "verbose_name": "зачетная таблица",
                "verbose_name_plural": "зачетные таблицы",
            },
        ),
    ]
