# Generated by Django 5.0.2 on 2024-05-05 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("checkpoints", "0005_alter_checkpoint_options_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="checkpoint",
            table="checkpoints",
        ),
        migrations.AlterModelTable(
            name="passedcheckpoint",
            table="passed_checkpoints",
        ),
        migrations.AlterModelTable(
            name="summary",
            table="summaries",
        ),
    ]
