# Generated by Django 5.0.2 on 2024-05-09 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("checkpoints", "0007_alter_checkpoint_checkpoint_number_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="checkpoint",
            old_name="title",
            new_name="name",
        ),
    ]
