# Generated by Django 5.0.2 on 2024-05-21 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checkpoints", "0008_rename_title_checkpoint_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkpoint",
            name="total",
            field=models.IntegerField(default=0, verbose_name="всего"),
            preserve_default=False,
        ),
    ]
