# Generated by Django 5.0.2 on 2024-05-03 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_course_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="course",
            options={"verbose_name": "курс", "verbose_name_plural": "курсы"},
        ),
        migrations.AlterModelOptions(
            name="enrollment",
            options={
                "verbose_name": "связь студента и курса",
                "verbose_name_plural": "связь студентов и курсов",
            },
        ),
        migrations.AlterModelOptions(
            name="lesson",
            options={"verbose_name": "урок", "verbose_name_plural": "уроки"},
        ),
        migrations.AlterModelOptions(
            name="lessonotherfile",
            options={
                "verbose_name": "дополнительный файл",
                "verbose_name_plural": "дополнительные файлы",
            },
        ),
        migrations.AlterModelOptions(
            name="module",
            options={"verbose_name": "модуль", "verbose_name_plural": "модули"},
        ),
    ]
