# Generated by Django 5.0.2 on 2024-05-05 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0004_alter_course_options_alter_enrollment_options_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="course",
            table="courses",
        ),
        migrations.AlterModelTable(
            name="enrollment",
            table="enrollments",
        ),
        migrations.AlterModelTable(
            name="lesson",
            table="lessons",
        ),
        migrations.AlterModelTable(
            name="lessonotherfile",
            table="lesson_other_files",
        ),
        migrations.AlterModelTable(
            name="module",
            table="modules",
        ),
    ]
