# Generated by Django 5.0.2 on 2024-05-09 18:12

import courses.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0005_alter_course_table_alter_enrollment_table_and_more"),
        ("profiles", "0004_alter_studentprofile_user_alter_teacherprofile_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="course_name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="название курса"
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="course_password",
            field=models.CharField(
                blank=True, default="", max_length=50, verbose_name="пароль курса"
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="дата создания"),
        ),
        migrations.AlterField(
            model_name="course",
            name="description",
            field=models.TextField(
                blank=True, max_length=10000, null=True, verbose_name="описание"
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="courses/", verbose_name="изображение"
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="status",
            field=models.BooleanField(default=True, verbose_name="статус"),
        ),
        migrations.AlterField(
            model_name="course",
            name="teacher_profile",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="courses",
                to="profiles.teacherprofile",
                verbose_name="профиль преподавателя",
            ),
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="enrollments",
                to="courses.course",
                verbose_name="курс",
            ),
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="enrollment_date",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="дата зачисления"
            ),
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="enrollments",
                to="profiles.studentprofile",
                verbose_name="студент",
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="дата создания"),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="description",
            field=models.TextField(
                blank=True, max_length=10000, null=True, verbose_name="описание"
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="lesson_name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="название урока"
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="module",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="videos",
                to="courses.module",
                verbose_name="модуль",
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="status",
            field=models.BooleanField(default=True, verbose_name="статус"),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="video",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=courses.models.lesson_video_directory_path,
                verbose_name="видео",
            ),
        ),
        migrations.AlterField(
            model_name="lessonotherfile",
            name="lesson",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="other_files",
                to="courses.lesson",
                verbose_name="урок",
            ),
        ),
        migrations.AlterField(
            model_name="lessonotherfile",
            name="other_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=courses.models.other_file_directory_path,
                verbose_name="дополнительный файл",
            ),
        ),
        migrations.AlterField(
            model_name="module",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="modules",
                to="courses.course",
                verbose_name="курс",
            ),
        ),
        migrations.AlterField(
            model_name="module",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="дата создания"),
        ),
        migrations.AlterField(
            model_name="module",
            name="module_name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="название модуля"
            ),
        ),
        migrations.AlterField(
            model_name="module",
            name="status",
            field=models.BooleanField(default=True, verbose_name="статус"),
        ),
    ]
