# Generated by Django 5.0.2 on 2024-05-09 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0006_alter_course_course_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="module",
            name="module_name",
        ),
        migrations.AddField(
            model_name="module",
            name="name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="название"
            ),
        ),
    ]
