# Generated by Django 5.0.2 on 2024-05-09 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0007_remove_module_module_name_module_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lesson",
            name="lesson_name",
        ),
        migrations.AddField(
            model_name="lesson",
            name="name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="название"
            ),
        ),
    ]
