# Generated by Django 5.0.2 on 2024-05-05 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0003_alter_customuser_username"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="customuser",
            table="users",
        ),
    ]
