# Generated by Django 5.0.2 on 2024-04-16 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('checkpoints', '0001_initial'),
        ('profiles', '0001_initial'),
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryOfPassedAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='questions.answer')),
                ('checkpoint', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='checkpoints.passedcheckpoint')),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='questions.question')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.studentprofile')),
            ],
        ),
    ]
