# Generated by Django 5.0.2 on 2024-04-15 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("history", "0001_initial"),
        ("questions", "0002_alter_answer_id_alter_answerfile_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historyofpassedanswer",
            name="answer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="questions.answer",
            ),
        ),
    ]
