# Generated by Django 5.0.2 on 2024-04-16 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("history", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="historyofpassedanswer",
            old_name="answer",
            new_name="selected_answer",
        ),
    ]
