# Generated by Django 5.0.2 on 2024-04-21 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("history", "0004_historyofpassedanswer_is_correct"),
    ]

    operations = [
        migrations.AddField(
            model_name="historyofpassedanswer",
            name="points",
            field=models.IntegerField(default=0),
        ),
    ]
