# Generated by Django 5.0.2 on 2024-04-29 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("history", "0005_historyofpassedanswer_points"),
    ]

    operations = [
        migrations.AddField(
            model_name="historyofpassedanswer",
            name="attempt_number",
            field=models.IntegerField(default=1),
        ),
    ]
