# Generated by Django 5.0.2 on 2024-05-03 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("history", "0006_historyofpassedanswer_attempt_number"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historyofpassedanswer",
            options={
                "verbose_name": "история прохождения вопроса",
                "verbose_name_plural": "история прохождения вопросов",
            },
        ),
    ]
