# Generated by Django 5.0.2 on 2024-05-05 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("history", "0007_alter_historyofpassedanswer_options"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="historyofpassedanswer",
            table="history_of_passed_answers",
        ),
    ]
