# Generated by Django 5.0.2 on 2024-05-12 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("checkpoints", "0008_rename_title_checkpoint_name"),
        ("history", "0009_alter_historyofpassedanswer_attempt_number_and_more"),
        ("profiles", "0006_studentprofile_is_teacher_teacherprofile_is_teacher"),
        ("questions", "0004_alter_answer_answer_text_alter_answer_is_correct_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="HistoryOfPassedAnswer",
            new_name="HistoryOfSelectedAnswer",
        ),
    ]
