# Generated by Django 5.0.2 on 2024-05-12 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("history", "0010_rename_historyofpassedanswer_historyofselectedanswer"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historyofselectedanswer",
            options={
                "verbose_name": "история выбора ответа",
                "verbose_name_plural": "история выбора ответов",
            },
        ),
        migrations.AlterModelTable(
            name="historyofselectedanswer",
            table="history_of_selected_answers",
        ),
    ]
