# Generated by Django 5.0.2 on 2024-03-21 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courseapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="lessonvideo",
            old_name="lesson",
            new_name="module",
        ),
    ]
