# Generated by Django 5.0.2 on 2024-03-03 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courseapp', '0002_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='teacher_profile',
            new_name='teacher_id',
        ),
    ]
