# Generated by Django 5.0.2 on 2024-03-03 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courseapp', '0003_rename_teacher_profile_course_teacher_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='teacher_id',
            new_name='teacher',
        ),
    ]
