# Generated by Django 5.0.2 on 2024-03-22 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courseapp", "0003_rename_lesson_name_module_module_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="lessonvideo",
            name="lesson_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
