# Generated by Django 5.0.2 on 2024-03-03 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courseapp", "0004_rename_teacher_id_course_teacher"),
    ]

    operations = [
        migrations.RenameField(
            model_name="course",
            old_name="teacher",
            new_name="teacher_profile",
        ),
    ]
