# Generated by Django 5.0.2 on 2024-03-25 18:09

import courseapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courseapp", "0005_rename_lessonvideo_lesson_lessonotherfile"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="status",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="lessonotherfile",
            name="other_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=courseapp.models.other_file_directory_path,
            ),
        ),
    ]
