# Generated by Django 5.0.2 on 2024-03-05 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courseapp", "0007_studentprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacherprofile",
            name="avatar",
            field=models.FileField(null=True, upload_to="teacher-avatars/"),
        ),
    ]
