# Generated by Django 5.0.2 on 2024-03-05 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courseapp", "0008_teacherprofile_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="avatar",
            field=models.FileField(null=True, upload_to="student-avatars/"),
        ),
    ]
