# Generated by Django 5.0.2 on 2024-03-06 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courseapp", "0009_studentprofile_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
