# Generated by Django 5.0.2 on 2024-03-06 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courseapp", "0012_video_video"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacherprofile",
            name="avatar",
            field=models.FileField(blank=True, null=True, upload_to="teacher-avatars/"),
        ),
    ]
