# Generated by Django 5.0.2 on 2024-03-06 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courseapp", "0015_rename_name_course_course_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentprofile",
            name="avatar",
            field=models.FileField(blank=True, null=True, upload_to="student-avatars/"),
        ),
    ]
