# Generated by Django 5.0.2 on 2024-03-07 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courseapp", "0019_answer"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="teacherprofile",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
