# Generated by Django 5.0.2 on 2024-03-08 06:35

import courseapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courseapp", "0021_enrollment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="video",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=courseapp.models.course_video_directory_path,
            ),
        ),
    ]
