# Generated by Django 5.0.2 on 2024-03-12 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courseapp", "0022_alter_video_video"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Video",
            new_name="Lesson",
        ),
    ]
