# Generated by Django 5.0.2 on 2024-03-14 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courseapp", "0025_course_created_at_lesson_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="max_points",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
