# Generated by Django 5.0.2 on 2024-03-14 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courseapp", "0027_historyoftestpass"),
    ]

    operations = [
        migrations.CreateModel(
            name="PassedTest",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("points", models.IntegerField()),
                ("percent", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="passed_tests",
                        to="courseapp.studentprofile",
                    ),
                ),
                (
                    "test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="passed_tests",
                        to="courseapp.test",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="HistoryOfTestPass",
        ),
    ]
