# Generated by Django 5.0.2 on 2024-03-15 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courseapp", "0028_passedtest_delete_historyoftestpass"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="course_password",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
    ]
