# Generated by Django 5.0.2 on 2024-03-15 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courseapp", "0031_alter_course_course_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentprofile",
            name="avatar",
            field=models.ImageField(
                blank=True, null=True, upload_to="student-avatars/"
            ),
        ),
        migrations.AlterField(
            model_name="teacherprofile",
            name="avatar",
            field=models.ImageField(
                blank=True, null=True, upload_to="teacher-avatars/"
            ),
        ),
    ]
