# Generated by Django 5.0.2 on 2024-03-28 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courseapp", "0001_initial"),
        ("userapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CheckPoint",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("checkpoint_number", models.IntegerField()),
                ("title", models.TextField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checkpoint",
                        to="courseapp.module",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PassedCheckPoint",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("points", models.IntegerField()),
                ("percent", models.FloatField(blank=True, null=True)),
                ("status", models.CharField(blank=True, max_length=255, null=True)),
                ("grade", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "checkpoint",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="passed_checkpoints",
                        to="checkpointapp.checkpoint",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="passed_checkpoints",
                        to="userapp.studentprofile",
                    ),
                ),
            ],
        ),
    ]
