# Generated by Django 5.0.2 on 2024-03-21 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("checkpointapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="checkpoint",
            old_name="lesson",
            new_name="module",
        ),
    ]
