# Generated by Django 5.0.2 on 2024-04-07 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checkpointapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="summary",
            name="grade",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
