# Generated by Django 5.0.2 on 2024-03-21 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checkpointapp", "0002_rename_lesson_checkpoint_module"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answer",
            name="answer_text",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
