# Generated by Django 5.0.2 on 2024-03-17 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checkpointapp", "0002_alter_passedcheckpoint_checkpoint_and_more"),
        ("courseapp", "0002_enrollment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="checkpoint",
            name="lesson",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="checkpoint",
                to="courseapp.lesson",
            ),
        ),
    ]
