# Generated by Django 5.0.2 on 2024-03-20 15:52

import checkpointapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checkpointapp", "0003_alter_checkpoint_lesson"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="question_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=checkpointapp.models.question_file_directory_path,
            ),
        ),
    ]
