# Generated by Django 5.0.2 on 2024-03-22 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checkpointapp", "0003_alter_answer_answer_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passedcheckpoint",
            name="percent",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
