# Generated by Django 5.0.2 on 2024-03-28 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checkpointapp", "0003_summary_current_points"),
    ]

    operations = [
        migrations.AlterField(
            model_name="summary",
            name="current_points",
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
