# Generated by Django 5.0.2 on 2024-03-22 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checkpointapp", "0004_alter_passedcheckpoint_percent"),
    ]

    operations = [
        migrations.AddField(
            model_name="passedcheckpoint",
            name="status",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
