# Generated by Django 5.0.2 on 2024-03-20 16:05

import checkpointapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checkpointapp", "0004_question_question_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="answer_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=checkpointapp.models.answer_file_directory_path,
            ),
        ),
    ]
