# Generated by Django 5.0.2 on 2024-03-22 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checkpointapp", "0005_passedcheckpoint_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="passedcheckpoint",
            name="grade",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
