# Generated by Django 5.0.2 on 2024-03-20 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checkpointapp", "0005_answer_answer_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answer",
            name="answer_text",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
