# Generated by Django 5.0.2 on 2024-03-20 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checkpointapp", "0006_alter_answer_answer_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkpoint",
            name="checkpoint_number",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
