# Generated by Django 5.0.2 on 2024-03-20 16:29

import checkpointapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checkpointapp", "0008_remove_answer_answer_file_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answerimages",
            name="image",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=checkpointapp.models.answer_file_directory_path,
            ),
        ),
        migrations.AlterField(
            model_name="questionimages",
            name="image",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=checkpointapp.models.question_file_directory_path,
            ),
        ),
    ]
