# Generated by Django 5.0.2 on 2024-03-20 16:52

import checkpointapp.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "checkpointapp",
            "0010_rename_answerimages_answerimage_questionimage_and_more",
        ),
    ]

    operations = [
        migrations.RenameModel(
            old_name="QuestionImage",
            new_name="QuestionFile",
        ),
        migrations.CreateModel(
            name="AnswerFile",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "answer_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=checkpointapp.models.answer_file_directory_path,
                    ),
                ),
                (
                    "answer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answer_files",
                        to="checkpointapp.answer",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="AnswerImage",
        ),
    ]
