# Generated by Django 5.0.2 on 2024-04-02 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userapp", "0002_studentprofile_email_teacherprofile_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="last_login",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="last login"
            ),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="password",
            field=models.CharField(default=0, max_length=128, verbose_name="password"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="teacherprofile",
            name="last_login",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="last login"
            ),
        ),
        migrations.AddField(
            model_name="teacherprofile",
            name="password",
            field=models.CharField(default=0, max_length=128, verbose_name="password"),
            preserve_default=False,
        ),
    ]
