# Generated by Django 5.0.2 on 2024-04-02 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("userapp", "0003_studentprofile_last_login_studentprofile_password_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studentprofile",
            name="email",
        ),
        migrations.RemoveField(
            model_name="studentprofile",
            name="last_login",
        ),
        migrations.RemoveField(
            model_name="studentprofile",
            name="password",
        ),
        migrations.RemoveField(
            model_name="teacherprofile",
            name="email",
        ),
        migrations.RemoveField(
            model_name="teacherprofile",
            name="last_login",
        ),
        migrations.RemoveField(
            model_name="teacherprofile",
            name="password",
        ),
    ]
